Instalar la librería Numpy

In [ ]:
!pip install numpy

Importar Librerías numpy y pandas


In [ ]:
import numpy as np
import pandas as pd


Declarar una variable y asignarle un valor numérico.
Elaborar una estructura de control, utilizando if then.. else if.. else.

In [1]:
edad = 25

# Estructura de control
if edad < 18:
    print("Eres menor de edad.")
elif edad >= 18 and edad < 65:
    print("Eres adulto.")
else:
    print("Eres adulto mayor.")


Eres adulto.


Crear una función que devuelva la suma de 3 números enteros.

In [2]:
def sumar_tres_numeros(a, b, c):
    return a + b + c

Llamar a la función que suma 3 números enteros.

In [3]:
resultado = sumar_tres_numeros(7, 12, 5)

print("La suma es:", resultado)

La suma es: 24


Llamar a la función que suma 3 números enteros, pero pasar argumentos de tipo "string"

In [4]:
resultado = sumar_tres_numeros("5", "10", "15")
print("Resultado:", resultado)


Resultado: 51015


Un inversor financiero está interesado en invertir en la compañía. Se propone comprar durante cada día de la semana 20 acciones. También sabe que la probabilidad de obtener ganancias (aproximadamente 15% en cada inversión) es de 0.56 y la probabilidad de perder el 18% es 0.44 (Solo hay esas dos opciones).
Crear una función llamada retorno_semanal que calcule el valor esperado con la cantidad de acciones compradas cada día, probabilidad de ganancia y no ganancia

In [ ]:
valores= [200, 225, 232, 221, 243, 256, 255]

In [12]:
def retorno_semanal(valores, acciones_por_dia=20, prob_ganancia=0.56, retorno_ganancia=0.15, prob_perdida=0.44, retorno_perdida=-0.18):
    retorno_total = 0
    for precio in valores:
        inversion_diaria = precio * acciones_por_dia
        retorno_esperado = inversion_diaria * (prob_ganancia * retorno_ganancia + prob_perdida * retorno_perdida)
        retorno_total += retorno_esperado
    return retorno_total
valores = [200, 225, 232, 221, 243, 256, 255]
resultado = retorno_semanal(valores)
print(f"Retorno esperado semanal: ${resultado:.2f}")

Retorno esperado semanal: $156.67


Crear una variable, asignar valor "None"

In [13]:
mi_variable = None

Imprimir la variable cuyo valor es "None"

In [14]:
resultado = None
if resultado is None:
    print("Todavía no se ha calculado el resultado.")

Todavía no se ha calculado el resultado.


Crear un arreglo, con valores de distinto tipo (numérico y texto), luego mostrar el contenido del arreglo.

In [15]:
mi_arreglo = [42, "Uruguay", 3.14, "Montevideo", -7]
print("Contenido del arreglo:", mi_arreglo)

Contenido del arreglo: [42, 'Uruguay', 3.14, 'Montevideo', -7]


# Numpy
Importar la librería Numpy, con el alias np

In [16]:
import numpy as np

Crear un arreglo con valores numéricos del 0 al 9. Mostrar el contenido del arreglo.

In [18]:
arreglo = np.arange(10)
print("Contenido del arreglo:", arreglo)

Contenido del arreglo: [0 1 2 3 4 5 6 7 8 9]


Crear un arreglo con n-valores numéricos 0. Mostrar el contenido del arreglo.

In [19]:
n = 10
arreglo = np.zeros(n)
print("Arreglo con", n, "ceros:", arreglo)


Arreglo con 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crear un arreglo con n-valores numéricos 1. Mostrar el contenido del arreglo.

In [20]:
n = 10

arreglo = np.ones(n)

print("Arreglo con", n, "unos:", arreglo)


Arreglo con 10 unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Crear un arreglo con n-valores numéricos, definiendo el número que se va a guardar. Mostrar el contenido del arreglo.

In [21]:
n = 10
numero = 7

arreglo = np.full(n, numero)

print("Arreglo con", n, "valores iguales a", numero, ":", arreglo)


Arreglo con 10 valores iguales a 7 : [7 7 7 7 7 7 7 7 7 7]


Crear un arreglo con valores numéricos del 0 al 9 (con arange). Mostrar el contenido del arreglo.

In [22]:
arreglo = np.arange(10)
print(arreglo)


[0 1 2 3 4 5 6 7 8 9]


Crear un arreglo matricial de 2 x 3, con valores numéricos random de 0 .. 9. Mostrar el contenido del arreglo.

In [23]:
arreglo = np.random.randint(0, 10, size=(2, 3))
print(arreglo)


[[8 8 9]
 [6 4 2]]


Crear un arreglo matricial de 2 x 7, con valores numéricos random de 0 .. 99. Mostrar el contenido del arreglo.

In [24]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo)


[[14 98 41 58 69 41 46]
 [33 13 12 61  3 17 22]]


Mostrar la dimensión de la matriz.

In [25]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo)
print("Dimensión de la matriz:", arreglo.shape)


[[13 66 80 68  3 15  5]
 [68 35 96 81 94 86 93]]
Dimensión de la matriz: (2, 7)


Mostrar la forma de la matriz (cuántas filas y cuántas columnas)

In [26]:
arreglo = np.random.randint(0, 100, size=(2, 7))
filas, columnas = arreglo.shape
print("Filas:", filas)
print("Columnas:", columnas)

Filas: 2
Columnas: 7


Mostrar el tamaño (cantidad de elementos) de la matriz.

In [27]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo.size)

14


Mostrar el tipo de elementos de los valores de la matriz.

In [28]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo.dtype)

int64


Mostrar el espacio en memoria que ocupa cada elemento de la matriz.

In [29]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo.itemsize)


8


Mostrar el tamaño en bytes de la matriz.

In [30]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo.nbytes)

112


Mostrar el elemento de la fila 2, columna 5

In [31]:
arreglo = np.random.randint(0, 100, size=(2, 7))
print(arreglo[1, 4])

48


Usar el arreglo con valores numéricos del 0 al 9.
Para ese arreglo, mostrar los elementos pares, comenzando desde la posición inicial.

In [32]:
arreglo = np.arange(10)
pares = arreglo[arreglo % 2 == 0]
print(pares)


[0 2 4 6 8]


# Pandas
Importar la librería Pandas, con el alias pd

In [33]:
import pandas as pd

Crear un arreglo con valores numéricos del 0 al 9. Mostrar el contenido del arreglo.

In [34]:
arreglo = np.arange(10)
print(arreglo)

[0 1 2 3 4 5 6 7 8 9]


Dado el siguiente set de datos:

Columnas = "A", "B" y "C"
Valores para cada columna = [1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [1, 8 , 6 ,7 ,6]

Organizarlos en un data frame Pandas.

In [35]:
data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50], 'C': [1, 8 , 6 ,7 ,6]}
datos = {
    "A": [1, 2, 3, 4, 5],
    "B": [10, 20, 30, 40, 50],
    "C": [1, 8, 6, 7, 6]
}

df = pd.DataFrame(datos)
print(df)


   A   B  C
0  1  10  1
1  2  20  8
2  3  30  6
3  4  40  7
4  5  50  6


Mostrar el data frame Pandas creado en el paso anterior.

In [36]:
print(df)

   A   B  C
0  1  10  1
1  2  20  8
2  3  30  6
3  4  40  7
4  5  50  6


Enumerar las columnas del data frame.

In [37]:
print(df.columns.tolist())

['A', 'B', 'C']


Enumerar los índices del data frame.

In [38]:
print(df.index.tolist())

[0, 1, 2, 3, 4]


Mostrar los valores de todas las columnas, para la fila 1, como arreglo.

In [39]:
print(df.iloc[0].values)

[ 1 10  1]


Mostrar los valores de todas las columnas, para la fila 2, como arreglo Pandas.

In [40]:
print(df.iloc[1])

A     2
B    20
C     8
Name: 1, dtype: int64


Mostrar la columna "B", y los índices menores que 3.

In [41]:
print(df.loc[df.index < 3, "B"])

0    10
1    20
2    30
Name: B, dtype: int64


Re-escribir el filtro, anidando en un sólo bloque.

In [42]:
print(df[df.index < 3]["B"])

0    10
1    20
2    30
Name: B, dtype: int64


Trasponer el data frame.

In [43]:
print(df.T)

    0   1   2   3   4
A   1   2   3   4   5
B  10  20  30  40  50
C   1   8   6   7   6


Obtener un dataframe, a partir de la suma de las columnas A y B del dataframe anterior.

In [44]:
df_suma = pd.DataFrame(df["A"] + df["B"], columns=["A+B"])
print(df_suma)

   A+B
0   11
1   22
2   33
3   44
4   55


Crear y asignar valores:

1 arreglo) Numeros_3 = range(51,70,2)

2 arreglo) Numeros_4 = range(1,15,3)

Usar esos arreglos para crear las correspondientes Series de Pandas.

In [45]:
Numeros_3 = range(51,70,2)
Numeros_4 = range(1,15,3)
Numeros_3 = pd.Series(range(51, 70, 2))
Numeros_4 = pd.Series(range(1, 15, 3))
print(Numeros_3)
print(Numeros_4)

0    51
1    53
2    55
3    57
4    59
5    61
6    63
7    65
8    67
9    69
dtype: int64
0     1
1     4
2     7
3    10
4    13
dtype: int64


Crear una serie llamada "numeros_nan", resultado de multiplicar las 2 series creadas en el ejercicio anterior.

In [46]:
numeros_nan = Numeros_3 * Numeros_4
print(numeros_nan)

0     51.0
1    212.0
2    385.0
3    570.0
4    767.0
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
dtype: float64


Multiplicar un numpy.nan * otro número cualquiera

In [47]:
resultado = np.nan * 5
print(resultado)

nan


Sumar un numpy.nan * otro número cualquiera

In [48]:
resultado = np.nan + 5
print(resultado)

nan


Multiplicar varios números enteros, usando el método nanprod. Ver qué pasa si uno de esos valores enteros se reemplaza por np.nan

In [50]:
valores = [2, 3, 4]
resultado = np.nanprod(valores)
print(resultado)
valores = [2, np.nan, 4]
resultado = np.nanprod(valores)
print(resultado)  # Salida: 8


24
8.0


Sumar varios números enteros, usando el método nanprod. Ver qué pasa si uno de esos valores enteros se reemplaza por np.nan

In [51]:
valores = [2, 4, 6]
print(np.nanprod(valores))
valores_con_nan = [2, np.nan, 6]
print(np.nanprod(valores_con_nan))


48
12.0


verificar qué valor es null en el data frame numeros_nan

In [52]:
print(numeros_nan.isna())

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
9     True
dtype: bool


Con el método fillna, reemplazar los valores vacíos por el entero 23.

In [53]:
numeros_nan = numeros_nan.fillna(23)
print(numeros_nan)

0     51.0
1    212.0
2    385.0
3    570.0
4    767.0
5     23.0
6     23.0
7     23.0
8     23.0
9     23.0
dtype: float64


Usar el método dropna para eliminar los valores vacíos del data frame numeros_nan

In [54]:
numeros_nan = numeros_nan.dropna()
print(numeros_nan)

0     51.0
1    212.0
2    385.0
3    570.0
4    767.0
5     23.0
6     23.0
7     23.0
8     23.0
9     23.0
dtype: float64
